public class Test3 {
    public void method() {
        String s = '' + 123;
        integer  a = 1;
        String s = '' + 123;
        integer  a = 1;
        String s = '' + 123;
        integer  a = 1;
        String s = '' + 123;
        integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
         integer  a = 1;
        String s = '' + 123;
        
    }
}
